### ISSUE TITLE
Knöpfe am Anfang der loop auslesen

### ISSUE THREAD

**Issue by f00f** [leNique/uwr-ba-hupe#5]
Du hast gemeint, dass Du das jetz anders machst, über Variablen. Das bezog sich aber nur auf die Drücker, oder? Die Knöpfe liest Du nach wie vor mit digitalRead direkt ein, richtig?

Ich überlege, das alles am Anfang der loop auszulesen und in Variablen zu merken. Dann könnte ich nämlich meine analogen Knöpfe auf dem Shield verwenden.

Spricht da was dagegen?

**Comment by leNique** [comment]
ja da gehts nur um die Drücker der Hupe. Weil da das Problem besteht das
sie - ich würde sagen "flackern" während man sie nicht drückt.

Bei den normalen Knöpfen passiert das nicht - die bouncen höchstens
während man sie drückt

an der Stelle könnte man dann die Schiri Drücker auch mit auslesen.
Ich hab da gestern ja eine funktion gemacht die das Drücken erst nach 10ms
dauerdrücken in eine Variable liest.
Ich dachte auch das ich das schon eingecheckt hatte aber finds grad
nicht...

Am 21. März 2017 um 09:14 schrieb f00f <notifications@github.com>:

**Comment by f00f** [comment]
Ich hab's auch net gefunden und mich gewundert, weil Du's ja schon gesagt hattest.
Drum hab ich da auch noch net rumgefriemelt.

**Comment by f00f** [comment]
Ich hab jetz das Auslesen der Knöpfe an den Anfang der Dateien gezogen, aber sonst unverändert gelassen.
Hm, könnte man eigentlich gleich an den Anfang der loop machen, macht man ja eh immer...

**Comment by f00f** [comment]
PS: Hab ich gleich gemacht, aber noch nicht gepusht.
