### ISSUE TITLE
Drücker und Knöpfe debouncen

### ISSUE THREAD

**Issue by f00f** [leNique/uwr-ba-hupe#6]
Die Bibliothek heisst Bounce2 und gibt's hier:
* [Code](https://github.com/thomasfredericks/Bounce2)
* [Doku](https://github.com/thomasfredericks/Bounce2/wiki)

**Comment by leNique** [comment]
Danke. Hatte ich mir vorhin auch angesehen.

Wobei ich nicht weis ob das genau das richtige ist.
Weil mir gehts ja vor allem darum ein Signal das gar nicht da ist zu
verwerfen.
Ich vermute beim bouncen gehts darum mehrere Signal nur als ein Signal zu
werten.

2017-03-21 9:16 GMT+01:00 f00f <notifications@github.com>:

**Comment by f00f** [comment]
Ich dachte, da geht's um beides. Hab's aber jetz net durchgelesen.

**Comment by f00f** [comment]
Ok, kurze Recherche: Debouncen ist eigentlich nur das Filtern von mehrfachen Zustandswechseln beim Schließen des Kontakts. Ich würde aber nicht ausschließen, dass das hier trotzdem hilft, weil es ja ein Filter auf dem Signal ist.

Außerdem bin ich über [diese Seite](https://www.arduino.cc/en/Tutorial/DigitalPins) gestolpert, wo explizit steht, das Pins im INPUT Modus sehr empfindlich sein und eigentlich immer Störungen haben. Abhilfe: Pullup oder Pulldown (10K zu +5V bzw. GND). Keine Ahnung, ob Du schon so einen in der Schaltung hast.

**Comment by leNique** [comment]
ja das mit den pullups ist klar.
Bei den Tastern sind die Pullups auch aktiviert (lässt sich Softwarseitig
lösen da der arduino interne pullups für diesen zweck besitzt).

Bei den Schiri Drückern geht das nicht weil ich ja vom "alten"
Microkontroller das Signal bekomme und auslesen will. Ein zusätzlicher
Pullup oder Pulldown würde das Signal immer auf Low oder Hight ziehen und
wäre damit nicht auslesbar....
Das Problem ist dabei das entweder der integrierte Pullup im "alten"
Microkontroller schlecht ist oder das es durch das auslesen der
SchiriDrücker (die ja unterwasser sein können und trotzdem keinen totalen
scheis liefern) teilweise auch falsche Zustände weitergegeben werden.

Das wäre dann das nächste Projekt diesen "alten Controller auch zu tauschen
:)




Am 21. März 2017 um 10:57 schrieb f00f <notifications@github.com>:

**Comment by leNique** [comment]
wobei ich mich grad frag ob ich grad quatsch erzähl und der aktivierte
pullup doch auch da gar nicht schlecht wäre....

Am 21. März 2017 um 11:22 schrieb Nik T <n.tadda@gmail.com>:

**Comment by leNique** [comment]
ich hatte nur nicht auf sync gedrückt deshalb war die neue datei nicht da...

aber ich denk ich versuchs jetzt doch erst mal mit dem bounce2
weil so wies jetzt ist isses denk ich auch nicht soooo gut

Am 21. März 2017 um 11:30 schrieb Nik T <n.tadda@gmail.com>:

**Comment by f00f** [comment]
Bei mir tritt das "Flimmern" auch auf, ich hab aber auch nix an den Pins dran. Wie erwartet also. Und wie erwartet hilft da auch INPUT_PULLUP. Kannst ja mal testen, ob das auch was bringt, wenn der Mikrocontroller dran hängt.

**Comment by leNique** [comment]
hab ich gestern (glaub ich) getestet. Wenn man den PULLUP einschaltet hupt
die Hupe nicht mehr...
(Es kann auch sein das das an der Diode lag die ich eingelötet habe - und
wieder ausgelötet hab weils mit nicht gehupt hat.... - ich denk aber der
test war vor der diode)

Eigentlich macht der PULLUP dabei ja auch keinen sinn weil vom alten
microcontroller ja ein +5V Signal kommt und wenn das weg ist soll was
passieren. - tuts ja auch nur manchmal bricht das Signal für 1-10 ms weg


2017-03-22 2:34 GMT+01:00 f00f <notifications@github.com>:
